version: 0.0
os: linux
files:
  - source: TEST/build/
    destination: /var/www/html/
    
hooks:
  BeforeInstall:
    - location: scripts/clean_html_directory.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
